"use client";

/**
 * Statement History Audit — drop a folder's worth of statement PDFs;
 * everything parses locally, statements are grouped by account and checked
 * for gaps, overlaps, duplicates, and balance continuity; findings and
 * exports are produced without any byte leaving the device.
 */

import { useCallback, useMemo, useRef, useState } from "react";
import {
  audit,
  AuditResult,
  AuditSource,
  describeFinding,
} from "@parser/audit";
import { parseStatement } from "@parser/parse";
import { StatementParseError } from "@parser/types";
import type { ParsedStatement } from "@parser/types";
import { toAuditXlsxBytes, toCsv, toOfx } from "@exporters";
import { beacon } from "@/lib/beacon";
import { openAuditReport } from "@/lib/auditReport";
import { downloadBytes } from "@/lib/download";
import { extractPdf } from "@/lib/extractClient";
import { canExport, loadLicense } from "@/lib/license";
import { fmtUsd } from "@/lib/statement";
import { FREE_EXPORT_CAP } from "@/lib/site";

/** The bundled, fully synthetic sample set (generated by the fixture tool). */
const SAMPLE_FILES = [
  ...["01", "02", "03", "04", "05", "06", "08", "09", "10", "11", "12"].map(
    (m) => `sample-2025-${m}.pdf`,
  ),
  "sample-2025-10-extra.pdf",
];

interface FileProgress {
  name: string;
  status: "queued" | "parsing" | "done" | "error";
  detail?: string;
}

export function Audit() {
  const [progress, setProgress] = useState<FileProgress[]>([]);
  const [result, setResult] = useState<AuditResult | null>(null);
  const [active, setActive] = useState(0);
  const [verifiedOnly, setVerifiedOnly] = useState(true);
  const [busy, setBusy] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);

  const processFiles = useCallback(async (files: { name: string; data: () => Promise<ArrayBuffer> }[]) => {
    setBusy(true);
    setResult(null);
    setProgress(files.map((f) => ({ name: f.name, status: "queued" })));
    const sources: AuditSource[] = [];
    for (let i = 0; i < files.length; i++) {
      setProgress((p) => p.map((x, j) => (j === i ? { ...x, status: "parsing" } : x)));
      beacon({ event: "parse_attempt" });
      const sourceId = `file-${i + 1}`;
      try {
        const buf = await files[i].data();
        const { pages } = await extractPdf(buf);
        const statements: ParsedStatement[] = parseStatement(pages).statements;
        beacon({ event: "parse_success", template: statements[0].templateId, durationMs: 0 });
        sources.push({ sourceId, fileName: files[i].name, statements });
        setProgress((p) =>
          p.map((x, j) =>
            j === i
              ? {
                  ...x,
                  status: "done",
                  detail: `${statements.reduce((n, s) => n + s.transactions.length, 0)} tx · ${statements[0].reconciliation.status}`,
                }
              : x,
          ),
        );
      } catch (e) {
        const code = e instanceof StatementParseError ? e.code : "UNREADABLE";
        beacon({ event: "parse_failed", errorType: code });
        sources.push({ sourceId, fileName: files[i].name, errorCode: code });
        setProgress((p) => p.map((x, j) => (j === i ? { ...x, status: "error", detail: code } : x)));
      }
    }
    setResult(audit(sources));
    setActive(0);
    setBusy(false);
  }, []);

  const onFiles = useCallback(
    (list: FileList | File[]) => {
      const files = [...list]
        .filter((f) => f.name.toLowerCase().endsWith(".pdf"))
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((f) => ({ name: f.name, data: () => f.arrayBuffer() }));
      if (files.length) void processFiles(files);
    },
    [processFiles],
  );

  const loadSample = useCallback(() => {
    void processFiles(
      SAMPLE_FILES.map((name) => ({
        name,
        data: async () => {
          const res = await fetch(`/samples/audit/${name}`);
          return res.arrayBuffer();
        },
      })),
    );
  }, [processFiles]);

  const account = result?.accounts[active];
  const exportLedger = useMemo(
    () => account?.ledger.filter((e) => !verifiedOnly || e.verified) ?? [],
    [account, verifiedOnly],
  );
  const license = typeof window !== "undefined" ? loadLicense() : { plan: "free" as const };
  const exportAllowed = canExport(license, exportLedger.length, FREE_EXPORT_CAP);

  const mergedStatement = useMemo((): ParsedStatement | null => {
    if (!account) return null;
    return {
      bankName: account.bankName,
      accountId: account.accountId,
      accountType: account.accountType,
      currency: account.currency,
      periodStart: account.coverageStart,
      periodEnd: account.coverageEnd,
      transactions: exportLedger.map((e) => e.tx),
      templateId: "audit-merge",
      reconciliation: {
        status: exportLedger.every((e) => e.verified) ? "verified" : "partial",
        transactionSumCents: exportLedger.reduce((s, e) => s + e.tx.amountCents, 0),
        creditSumCents: 0,
        debitSumCents: 0,
        flaggedRowIndices: [],
        notes: [],
      },
      warnings: [],
    };
  }, [account, exportLedger]);

  /* ── intake ──────────────────────────────────────────────────────── */
  if (!result) {
    return (
      <div>
        <div
          id="audit-drop"
          onDragOver={(e) => {
            e.preventDefault();
            setDragOver(true);
          }}
          onDragLeave={() => setDragOver(false)}
          onDrop={(e) => {
            e.preventDefault();
            setDragOver(false);
            onFiles(e.dataTransfer.files);
          }}
          className={`rounded-sm border-2 border-dashed px-6 py-14 text-center transition-colors ${
            dragOver ? "border-ledger bg-ledger-wash" : "border-rule-strong bg-surface"
          }`}
        >
          <p className="text-xl font-medium">Drop a year of statement PDFs here</p>
          <p className="mt-2 text-sm text-ink-soft">
            Select as many files as you like — they parse one by one in your
            browser, are grouped by account, and checked for gaps, duplicates,
            and balance continuity. Nothing uploads.
          </p>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <button
              type="button"
              onClick={() => fileInput.current?.click()}
              className="rounded-sm bg-ink px-5 py-2.5 text-sm font-medium text-white hover:bg-ink/85"
            >
              Choose PDFs
            </button>
            <button
              type="button"
              onClick={loadSample}
              disabled={busy}
              className="rounded-sm border border-ledger px-5 py-2.5 text-sm font-medium text-ledger hover:bg-ledger hover:text-white disabled:opacity-50"
            >
              Try a sample 12-month audit
            </button>
          </div>
          <input
            ref={fileInput}
            type="file"
            multiple
            accept="application/pdf,.pdf"
            className="sr-only"
            aria-label="Choose statement PDFs"
            onChange={(e) => {
              if (e.target.files) onFiles(e.target.files);
              e.target.value = "";
            }}
          />
        </div>

        {progress.length > 0 && (
          <ul className="figures mt-4 space-y-1 text-sm" aria-live="polite">
            {progress.map((f) => (
              <li key={f.name} className="flex justify-between gap-4 border-b border-rule py-1">
                <span className="truncate">{f.name}</span>
                <span
                  className={
                    f.status === "error"
                      ? "text-negative"
                      : f.status === "done"
                        ? "text-ledger"
                        : "text-ink-soft"
                  }
                >
                  {f.status === "parsing" ? "parsing…" : (f.detail ?? f.status)}
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>
    );
  }

  /* ── results ─────────────────────────────────────────────────────── */
  const issueKinds = new Set([
    "missing-period",
    "overlap",
    "duplicate-statement",
    "balance-discontinuity",
    "duplicate-transaction",
    "large-transaction",
  ]);
  const issues = result.findings.filter((f) => issueKinds.has(f.kind));
  const patterns = result.findings.filter((f) => f.kind === "recurring" || f.kind === "fee");

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <p className="figures text-sm text-ink-soft" data-testid="audit-summary">
          {progress.length} files · {result.accounts.length} account
          {result.accounts.length === 1 ? "" : "s"} ·{" "}
          {result.accounts.reduce((n, a) => n + a.ledger.length, 0)} transactions ·{" "}
          {issues.length} issue{issues.length === 1 ? "" : "s"} to review
        </p>
        <button
          type="button"
          onClick={() => {
            setResult(null);
            setProgress([]);
          }}
          className="rounded-sm border border-rule px-3 py-1.5 text-sm hover:border-rule-strong"
        >
          Start over
        </button>
      </div>

      {result.unparsed.length > 0 && (
        <div className="rounded-sm border border-negative bg-negative-wash p-4 text-sm">
          <p className="font-medium text-negative">
            {result.unparsed.length} file{result.unparsed.length === 1 ? "" : "s"} could not be
            read and {result.unparsed.length === 1 ? "is" : "are"} excluded from every result
            below:
          </p>
          <ul className="figures mt-1 list-inside list-disc">
            {result.unparsed.map((u) => (
              <li key={u.sourceId}>
                {u.fileName} — {u.errorCode}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Issues — the audit's headline output. */}
      <section aria-labelledby="issues-h">
        <h2 id="issues-h" className="text-xl font-semibold">
          Issues to review
        </h2>
        {issues.length === 0 ? (
          <p className="tape-in mt-3 rounded-sm border border-ledger-deep bg-ledger px-4 py-3 text-sm text-white">
            No gaps, duplicates, or balance discontinuities found across the
            verified statements.
          </p>
        ) : (
          <ul className="mt-3 space-y-2 text-sm">
            {issues.map((f, i) => (
              <li key={i} className="rounded-sm border border-caution bg-caution-wash px-3 py-2">
                {describeFinding(f)}
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Account tabs */}
      {result.accounts.length > 1 && (
        <div role="tablist" aria-label="Accounts" className="flex flex-wrap gap-2">
          {result.accounts.map((a, i) => (
            <button
              key={a.accountKey}
              role="tab"
              aria-selected={i === active}
              onClick={() => setActive(i)}
              className={`rounded-sm border px-3 py-1.5 text-sm ${
                i === active ? "border-ink bg-ink text-white" : "border-rule hover:border-rule-strong"
              }`}
            >
              {[a.bankName, a.accountType, a.accountId].filter(Boolean).join(" ")}
            </button>
          ))}
        </div>
      )}

      {account && (
        <>
          <section aria-labelledby="inv-h">
            <h2 id="inv-h" className="text-xl font-semibold">
              Statement inventory
            </h2>
            <div className="mt-3 overflow-x-auto rounded-sm border border-rule bg-surface">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-rule-strong bg-background text-left text-[11px] font-semibold uppercase tracking-wide text-ink-soft">
                    <th className="px-2 py-2">File</th>
                    <th className="px-2 py-2">Period</th>
                    <th className="px-2 py-2 text-right">Tx</th>
                    <th className="px-2 py-2">Status</th>
                    <th className="px-2 py-2 text-right">Opening</th>
                    <th className="px-2 py-2 text-right">Closing</th>
                  </tr>
                </thead>
                <tbody className="figures">
                  {account.inventory.map((i) => (
                    <tr key={i.sourceId} className="border-b border-rule">
                      <td className="truncate px-2 py-1.5">{i.fileName}</td>
                      <td className="px-2 py-1.5">
                        {i.periodStart} → {i.periodEnd}
                      </td>
                      <td className="px-2 py-1.5 text-right">{i.txCount}</td>
                      <td
                        className={`px-2 py-1.5 ${
                          i.status === "verified"
                            ? "text-ledger"
                            : i.status === "partial"
                              ? "text-caution"
                              : "text-negative"
                        }`}
                      >
                        {i.status}
                        {i.duplicateOf ? " · duplicate" : ""}
                      </td>
                      <td className="px-2 py-1.5 text-right">
                        {i.openingCents !== undefined ? fmtUsd(i.openingCents, account.currency) : "—"}
                      </td>
                      <td className="px-2 py-1.5 text-right">
                        {i.closingCents !== undefined ? fmtUsd(i.closingCents, account.currency) : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section aria-labelledby="mo-h">
            <h2 id="mo-h" className="text-xl font-semibold">
              Monthly cash flow
            </h2>
            <div className="mt-3 overflow-x-auto rounded-sm border border-rule bg-surface">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-rule-strong bg-background text-left text-[11px] font-semibold uppercase tracking-wide text-ink-soft">
                    <th className="px-2 py-2">Month</th>
                    <th className="px-2 py-2 text-right">Money in</th>
                    <th className="px-2 py-2 text-right">Money out</th>
                    <th className="px-2 py-2 text-right">Net</th>
                    <th className="px-2 py-2 text-right">Tx</th>
                  </tr>
                </thead>
                <tbody className="figures">
                  {account.monthly.map((m) => (
                    <tr key={m.month} className="border-b border-rule">
                      <td className="px-2 py-1.5">{m.month}</td>
                      <td className="px-2 py-1.5 text-right text-ledger">{fmtUsd(m.inCents)}</td>
                      <td className="px-2 py-1.5 text-right text-negative">{fmtUsd(m.outCents)}</td>
                      <td className="px-2 py-1.5 text-right">{fmtUsd(m.netCents)}</td>
                      <td className="px-2 py-1.5 text-right">{m.txCount}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}

      {patterns.length > 0 && (
        <section aria-labelledby="pat-h">
          <h2 id="pat-h" className="text-xl font-semibold">
            Recurring patterns & fees
          </h2>
          <ul className="mt-3 space-y-1.5 text-sm">
            {patterns.map((f, i) => (
              <li key={i} className="rounded-sm border border-rule bg-surface px-3 py-2">
                {describeFinding(f)}
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Exports */}
      <section aria-labelledby="exp-h" className="rounded-sm border border-rule bg-surface p-4">
        <h2 id="exp-h" className="text-lg font-semibold">
          Export
        </h2>
        <label className="mt-2 flex items-center gap-2 text-sm">
          <input
            type="checkbox"
            checked={verifiedOnly}
            onChange={(e) => setVerifiedOnly(e.target.checked)}
          />
          Verified statements only ({exportLedger.length} transactions
          {account && account.ledger.length !== exportLedger.length
            ? ` of ${account.ledger.length}`
            : ""}
          )
        </label>
        {!exportAllowed ? (
          <p className="mt-3 text-sm text-ink-soft">
            This merge has {exportLedger.length} transactions — the free plan
            exports up to {FREE_EXPORT_CAP} per file.{" "}
            <a href="/pricing/" className="underline" onClick={() => beacon({ event: "purchase_click" })}>
              See pricing
            </a>{" "}
            or activate a license key there; the full audit above stays free.
          </p>
        ) : (
          <div className="mt-3 flex flex-wrap gap-2 text-sm">
            <button
              type="button"
              disabled={!mergedStatement || exportLedger.length === 0}
              onClick={() => {
                downloadBytes("audit-merged.csv", toCsv(mergedStatement!), "text/csv");
                beacon({ event: "export", format: "csv" });
              }}
              className="rounded-sm bg-ledger px-3 py-2 font-medium text-white hover:bg-ledger-deep disabled:opacity-50"
            >
              Merged CSV ({exportLedger.length} transactions)
            </button>
            <button
              type="button"
              onClick={() => {
                downloadBytes(
                  "audit-workbook.xlsx",
                  toAuditXlsxBytes(result, { verifiedOnly }),
                  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                );
                beacon({ event: "export", format: "xlsx" });
              }}
              className="rounded-sm bg-ink px-3 py-2 font-medium text-white hover:bg-ink/85"
            >
              Audit workbook (XLSX, 6 sheets)
            </button>
            <button
              type="button"
              disabled={!mergedStatement || exportLedger.length === 0}
              onClick={() => {
                downloadBytes(
                  `audit-${account!.accountId?.replace(/\W/g, "") ?? "account"}.qbo`,
                  toOfx(mergedStatement!, {
                    flavor: "qbo",
                    accountType: account!.accountType === "credit-card" ? "CREDITCARD" : "CHECKING",
                    accountId: account!.accountId?.replace(/\D/g, "") || "0000",
                  }),
                  "application/x-ofx",
                );
                beacon({ event: "export", format: "qbo" });
              }}
              className="rounded-sm border border-ink px-3 py-2 font-medium hover:bg-ink hover:text-white disabled:opacity-50"
              title="One file per account — accounts are never merged into one QBO."
            >
              QBO (this account)
            </button>
            <button
              type="button"
              onClick={() => openAuditReport(result)}
              className="rounded-sm border border-rule px-3 py-2 hover:border-rule-strong"
            >
              Printable report
            </button>
          </div>
        )}
        <p className="mt-2 text-xs text-ink-soft">
          QBO/OFX exports are per account — unrelated accounts are never merged
          into one bank file.
        </p>
      </section>
    </div>
  );
}
